In [1]:
import numpy as np

## Esercizi sul registro
### Es 1
Creare una matrice 4x5 di numeri casuali. sottrai da ogni colonna la sua media e dividi per la sua deviazione standard (np.std)



In [27]:
matrix = np.random.uniform(0, 100, (4, 5))
matrix

array([[44.78371245, 88.48697834, 10.18188564, 63.37960211, 95.64067666],
       [66.77776593, 28.53820017, 50.24695049, 85.86272518, 91.5256018 ],
       [92.23253267, 99.77418762, 83.97094963, 56.19732578,  9.58087297],
       [93.98389417, 77.36493941, 13.80259046, 17.24641788, 93.20194126]])

In [28]:
mean=np.mean(matrix, axis=0)
mean

array([74.44447631, 73.54107638, 39.55059405, 55.67151774, 72.48727317])

In [29]:
matrix_standard=(matrix-mean)/np.std(matrix, axis=0)
matrix_standard

array([[-1.46629738,  0.55021873, -0.97718594,  0.31160068,  0.63698393],
       [-0.37900836, -1.65673678,  0.3559002 ,  1.22048492,  0.52377221],
       [ 0.87936307,  0.96574628,  1.47799986,  0.02125588, -1.73064689],
       [ 0.96594267,  0.14077177, -0.85671412, -1.55334148,  0.56989076]])

### es 2
data una matrice 6x6 di interi casuali tra -10 e 10, sostituisci tutti i valori negativi con 0, estrai solo le righe che hanno una somma maggiore di 15

In [67]:
matrix = np.random.randint(-10, 11, (6, 6))
matrix[(matrix<0)]=0
rows=matrix[(np.sum(matrix, axis=1))>15]
rows

array([[2, 0, 2, 6, 1, 7],
       [9, 0, 2, 8, 4, 0],
       [8, 4, 0, 5, 6, 1],
       [0, 3, 0, 7, 0, 9]])

### Es 3
dato un array di 100 temperature giornaliere casuali tra -5 e 35 °C: trova quanti giorni hanno temperatura tra 15 e 25 °C, sostituisci le temperature sotto 0 con 0 e sopra 30 con 30

In [72]:
temperature=np.random.uniform(-5, 35, 100)
temp15_25=np.count_nonzero((temperature>15) & (temperature<25))
temp15_25

18

In [74]:
temperature[temperature<0]=0
temperature[temperature>30]=30
temperature

array([18.34056655, 30.        ,  4.64344161, 26.8143309 , 30.        ,
       20.11765455, 11.75000752,  0.        , 13.30832672,  0.        ,
       28.93146365, 18.9435597 , 17.59444299, 18.05347004, 13.0331142 ,
        0.54969758,  0.43665772,  0.        ,  0.        ,  0.13255941,
        7.38418451, 14.18933972,  0.        , 11.44444139, 30.        ,
        7.11284275, 18.03553161,  5.90146682, 26.01573412,  0.        ,
       22.15067628,  0.        ,  7.58523366, 28.2482453 , 11.32847117,
       30.        ,  3.64175183,  0.41263242, 21.07421591, 20.75240605,
       14.95506079,  8.17708209, 14.10257528, 28.81675203, 26.79256282,
        0.        , 27.25644593,  0.87928439,  3.9469341 ,  0.        ,
       27.61144998,  8.57738518, 17.50662033, 30.        ,  9.15571726,
       28.90182063, 29.99835273, 30.        , 30.        , 14.0199798 ,
       30.        ,  0.        , 14.23390377, 30.        ,  0.        ,
       30.        ,  0.        , 30.        ,  1.87674525, 29.98